
--27-11-22

USE DATABASE SAMPLE_DATABASE;

SELECT CURRENT_DATE; --GET CURRENT DATE

SELECT CURRENT_TIMESTAMP; --GET CURRENT TIME --2022-11-27 02:09:57.649 -0800

--SNOWFLAKE IT DEPENDS ON THE TIEM ZONE THAT WE ARE 


SELECT CURRENT_TIME; --02:07:59

SELECT CONVERT_TIMEZONE('GMT',CURRENT_TIMESTAMP) AS GMT_TIMEZONE;

------------------------------------------------------

--BY USING DATE_TRUNC WE CAN GET ALL DATE MONTH AND YEAR AS THE FORMAT OF YYYY-MM-DD

SELECT DATE_TRUNC('YEAR',CURRENT_DATE) AS YEAR_FROM_DATE; --2022-01-01

SELECT DATE_TRUNC('MONTH',CURRENT_DATE) AS MONTH_FROM_DATE; --2022-11-01

SELECT DATE_TRUNC('DAY',CURRENT_DATE) AS DAY_FROM_DATE; -- GET THE DATE 2022-11-27

SELECT TO_DATE('2020-11-14') AS FAV_DATE; --TO_DATE function is used to convert the string into date format

SELECT DATE_TRUNC('DAY',TO_DATE('2020-11-14')) AS DAY_FROM_DATE;

SELECT DATE_TRUNC('WEEK',DATE('2022-11-27')) AS WEEK_DATE_FROM_DATE; --FOR WEEK ANALYSIS-- IT TAKES THE PERVIOUS MONDAYS DATE

---------------------------------------------------------------

SELECT DAY(CURRENT_TIMESTAMP()),
MONTH(CURRENT_TIMESTAMP()),
HOUR(CURRENT_TIMESTAMP()),
MINUTE(CURRENT_TIMESTAMP()),
SECOND(CURRENT_TIMESTAMP());



SELECT WEEK(CURRENT_DATE) AS WEEK_FROM_START_OF_THE_YEAR;

SELECT MONTH(CURRENT_DATE) AS MONTH_FROM_START_OF_THE_YEAR;

SELECT DAY(CURRENT_DATE) AS DAY_FROM_START_OF_THE_YEAR;

SELECT DAY(DATE('2022-11-14')) AS WEEK_FROM_START_OF_THE_YEAR;

-------------------------------------------------------

--GET LAST DAY OF PASSED MONTH

SELECT LAST_DAY(DATE('2022-11-14')) AS LAST_DAY_OF_GIVEN_MONTH;
-----------------------------------------------------------------------

--INTERVALS 

SELECT DATE(DATE('2022-11-17')-INTERVAL '5 day') AS FIVE_dAY_BACK_DATE;

SELECT DATE(DATE('2022-11-17')-INTERVAL '2 MONTH') AS TWO_month_BACK_DATE;

SELECT DATE(DATE('2022-11-17')-INTERVAL '2 WEEK') AS TWO_WEEK_BACK_DATE;

---------------------------------------------------------------------

--12 MONTHS = QUATER = 12/4 = 3 SO JAN,FEB,MAR= 1 QUATER

SELECT QUARTER(CURRENT_DATE) AS QTR;

-------------------------------------------------------------------

--BY USING EXTRACT WE GET ONLY WHAT WE HAVE SPECIFIED EITHER IT MAY BE DAY,MONTH OR YEAR.
SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS YEAR;
SELECT EXTRACT(MONTH FROM CURRENT_DATE) AS MONTH;
SELECT EXTRACT(DAY FROM CURRENT_DATE) AS DAY;

-----------------------------------------------------

--WE CAN CHANGE FORMAT AS PER THE REQUIREMENTS

SELECT TO_CHAR(TO_DATE('1993-10-12'),'DD-MM-YYYY') AS DATE_DD_MM_YYYY;--HIGHLY USED

SELECT TO_CHAR(TO_DATE(CURRENT_DATE),'DD-MM-YYYY') AS DATE_DD_MM_YYYY;

SELECT TO_CHAR(TO_DATE(CURRENT_DATE),'DY-DD-MM-YYYY') AS DATE_DD_MM_YYYY;

SELECT TO_CHAR(TO_DATE('1993-10-12'),'MM-YYYY') AS MONTH_MM_YYYY;

SELECT TO_CHAR(TO_DATE('1993-10-12'),'DD-YYYY') AS DAY_MM_YYYY;

SELECT TO_CHAR(TO_DATE('1993-10-12'),'DY') AS DATE_DD_MM_YYYY; -- DISPLAYS THE DAY 

------------------------------------------------------------------

SELECT DATEDIFF('MONTH','2022-06-01','2021-08-21');

SELECT DATEDIFF('MONTH','2020-11-14','2022-11-27') AS DIFFERENCE_IN_MONTHS;

SELECT DATEDIFF('DAYS','2020-11-14','2022-11-27') AS DIFFERENCE_IN_DAYS;

SELECT DATEDIFF('WEEK','2020-11-14','2022-11-27') AS DIFFERENCE_IN_WEEKS;

SELECT DATEDIFF('MINUTES','2020-11-14','2022-11-27') AS DIFFERENCE_IN_MINUTES;

SELECT DATEDIFF('SECOND','2020-11-14','2022-11-27') AS DIFFERENCE_IN_SECONDS;



------------------------------------------------------------------------------------
